// MAT Studio: data-loader.ts
// Loads the publication model JSON files generated by build-publication-model.mjs
// Also loads individual element record structured data from records/NNNN-Name-Symbol/

export interface ElementData {
  z: number;
  symbol: string;
  name: string;
  matId: string;
  period: number;
  group: number;
  block: string;
  category: string;
  recordStatus: 'CURATED' | 'BASELINE';
  hasFullRecord: boolean;
  atomicWeight: number | null;
  electronConfiguration: string | null;
  electronegativity: number | null;
  ionizationEnergy: number | null;
  phase: string | null;
  meltingPoint: number | null;
  boilingPoint: number | null;
  density: number | null;
  publishedRecord: boolean;
  chapterPath: string | null;
}

export interface RecordData {
  id: string;
  mat: string | null;
  title: string;
  section: string;
  lane: string;
}

export interface ElementRecord {
  registryId: string;
  recordId: string;
  recordVersion: string;
  created: string;
  updated: string;
  status: string;
  recordClass: string;
  schemaVersion: string;
  identity: {
    canonicalName: string;
    symbol: string;
    atomicNumber: number;
    matId: string;
    period: number;
    group: number | null;
    block: string;
    category: string;
  };
  properties: Record<string, any>;
  completeness: Record<string, string>;
}

export interface VisualManifest {
  registryId: string;
  recordId: string;
  manifestVersion: string;
  visuals: Record<string, {
    assetId: string;
    filename: string;
    path: string;
    status: string;
  }>;
}

export interface GraphManifest {
  recordId: string;
  manifestId: string;
  version: string;
  graphs: Array<{
    graphId: string;
    filename: string;
    dataFilename: string;
    title: string;
    status: string;
    sourceIds: string[];
  }>;
}

export interface TableManifest {
  recordId: string;
  manifestId: string;
  version: string;
  tables: Array<{
    tableId: string;
    filename: string;
    title: string;
    status: string;
  }>;
}

export interface MATData {
  elements: ElementData[];
  records: RecordData[];
  charts: any[];
  glossary: any[];
  metadata: any;
}

async function fetchJSON(path: string): Promise<any> {
  const resp = await fetch(path);
  if (!resp.ok) throw new Error(`Failed to load ${path}: ${resp.status}`);
  return resp.json();
}

async function fetchText(path: string): Promise<string | null> {
  try {
    const resp = await fetch(path);
    if (!resp.ok) return null;
    return resp.text();
  } catch {
    return null;
  }
}

// Simple YAML parser for structured element records
function parseSimpleYAML(text: string): any {
  const result: any = {};
  const lines = text.split('\n');
  let currentObj = result;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const match = trimmed.match(/^(\s*)([\w-]+):\s*(.*)/);
    if (!match) continue;

    const [, , key, value] = match;
    const lineIndent = line.length - line.trimStart().length;

    if (lineIndent === 0) {
      if (value) {
        result[key] = parseYAMLValue(value);
      } else {
        result[key] = {};
        currentObj = result[key];
      }
    } else if (lineIndent > 0 && currentObj) {
      if (value) {
        currentObj[key] = parseYAMLValue(value);
      } else {
        currentObj[key] = {};
      }
    }
  }

  return result;
}

function parseYAMLValue(value: string): any {
  const trimmed = value.trim();
  if (trimmed === 'null' || trimmed === '~') return null;
  if (trimmed === 'true') return true;
  if (trimmed === 'false') return false;
  if (/^-?\d+(\.\d+)?$/.test(trimmed)) return Number(trimmed);
  if ((trimmed.startsWith('"') && trimmed.endsWith('"')) ||
      (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

// Build record folder name from element data
function buildRecordFolder(el: ElementData): string {
  const z = String(el.z).padStart(4, '0');
  return `${z}-${el.name}-${el.symbol}`;
}

export async function loadData(): Promise<MATData> {
  const [elementsFile, recordsFile, chartsFile, glossaryFile, metadataFile] = await Promise.all([
    fetchJSON('/data/publication/generated/publication-elements.json'),
    fetchJSON('/data/publication/generated/publication-records.json'),
    fetchJSON('/data/publication/generated/publication-charts.json'),
    fetchJSON('/data/publication/generated/publication-glossary.json'),
    fetchJSON('/data/publication/generated/publication-metadata.json'),
  ]);

  return {
    elements: elementsFile.elements || [],
    records: recordsFile || [],
    charts: chartsFile.charts || [],
    glossary: glossaryFile.glossary || [],
    metadata: metadataFile,
  };
}

// Load structured record data for a specific element
export async function loadElementRecord(el: ElementData): Promise<{
  master: ElementRecord | null;
  visuals: VisualManifest | null;
  graphs: GraphManifest | null;
  tables: TableManifest | null;
}> {
  const folder = buildRecordFolder(el);
  const basePath = `/records/${folder}/data/structured`;

  const [masterText, visualsText, graphsText, tablesText] = await Promise.all([
    fetchText(`${basePath}/${folder}.yaml`),
    fetchText(`${basePath}/${folder}-Visual-Manifest.yaml`),
    fetchText(`${basePath}/${folder}-Graph-Manifest.yaml`),
    fetchText(`${basePath}/${folder}-Table-Manifest.yaml`),
  ]);

  return {
    master: masterText ? parseSimpleYAML(masterText) : null,
    visuals: visualsText ? parseSimpleYAML(visualsText) : null,
    graphs: graphsText ? parseSimpleYAML(graphsText) : null,
    tables: tablesText ? parseSimpleYAML(tablesText) : null,
  };
}

// Load all element record folders manifest
export async function loadAllElementRecords(): Promise<Array<{
  z: number;
  symbol: string;
  name: string;
  matId: string;
  folder: string;
  hasRecord: boolean;
}>> {
  const data = await loadData();
  return data.elements.map(el => ({
    z: el.z,
    symbol: el.symbol,
    name: el.name,
    matId: el.matId,
    folder: buildRecordFolder(el),
    hasRecord: el.recordStatus === 'CURATED' || el.hasFullRecord,
  }));
}
